global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'chronos-nodes'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chronos-node-1:8080', 'chronos-node-2:8081']
